<?php

namespace ContainerFvQ4Hep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yb3RvSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yb3Rv_S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yb3Rv_S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collaborateur' => ['privates', '.errored..service_locator.Yb3Rv_S.App\\Entity\\Collaborateur', NULL, 'Cannot autowire service ".service_locator.Yb3Rv_S": it needs an instance of "App\\Entity\\Collaborateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'collaborateur' => 'App\\Entity\\Collaborateur',
        ]);
    }
}
