framework:
    cache:
        # Uncomment this to enable cache
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_doctrine_dbal_provider: 'doctrine.system_cache_pool'
        pools:
            cache.performance:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
                public: false
                tags: false
