<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY2AnnPK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY2AnnPK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY2AnnPK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY2AnnPK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY2AnnPK\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y2AnnPK',
    'container.build_id' => 'd285e941',
    'container.build_time' => 1750490845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY2AnnPK');
