<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyBxWWs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyBxWWs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVyBxWWs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVyBxWWs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVyBxWWs\App_KernelDevDebugContainer([
    'container.build_hash' => 'VyBxWWs',
    'container.build_id' => '9d5bc755',
    'container.build_time' => 1750595571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyBxWWs');
