<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvQ4Hep\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvQ4Hep/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvQ4Hep.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvQ4Hep\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvQ4Hep\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvQ4Hep',
    'container.build_id' => '31bb16bb',
    'container.build_time' => 1750493576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvQ4Hep');
