<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_affectation_index' => [[], ['_controller' => 'App\\Controller\\AffectationController::index'], [], [['text', '/affectation/']], [], [], []],
    'app_affectation_new' => [[], ['_controller' => 'App\\Controller\\AffectationController::new'], [], [['text', '/affectation/new']], [], [], []],
    'app_affectation_show' => [['id'], ['_controller' => 'App\\Controller\\AffectationController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/affectation']], [], [], []],
    'app_affectation_edit' => [['id'], ['_controller' => 'App\\Controller\\AffectationController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/affectation']], [], [], []],
    'app_affectation_delete' => [['id'], ['_controller' => 'App\\Controller\\AffectationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/affectation']], [], [], []],
    'app_collaborateur_index' => [[], ['_controller' => 'App\\Controller\\CollaborateurController::index'], [], [['text', '/collaborateur/']], [], [], []],
    'app_collaborateur_new' => [[], ['_controller' => 'App\\Controller\\CollaborateurController::new'], [], [['text', '/collaborateur/new']], [], [], []],
    'app_collaborateur_show' => [['id'], ['_controller' => 'App\\Controller\\CollaborateurController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborateur']], [], [], []],
    'app_collaborateur_edit' => [['id'], ['_controller' => 'App\\Controller\\CollaborateurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/collaborateur']], [], [], []],
    'app_collaborateur_delete' => [['id'], ['_controller' => 'App\\Controller\\CollaborateurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborateur']], [], [], []],
    'api_collaborateurs' => [[], ['_controller' => 'App\\Controller\\CollaborateurController::apiIndex'], [], [['text', '/collaborateur/api/collaborateurs']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_mission_index' => [[], ['_controller' => 'App\\Controller\\MissionController::index'], [], [['text', '/mission/']], [], [], []],
    'app_mission_new' => [[], ['_controller' => 'App\\Controller\\MissionController::new'], [], [['text', '/mission/new']], [], [], []],
    'app_mission_show' => [['id'], ['_controller' => 'App\\Controller\\MissionController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], [], []],
    'app_mission_edit' => [['id'], ['_controller' => 'App\\Controller\\MissionController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], [], []],
    'app_mission_delete' => [['id'], ['_controller' => 'App\\Controller\\MissionController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], [], []],
];
