<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Collaborateur extends \App\Entity\Collaborateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actif' => [parent::class, 'actif', null],
        "\0".parent::class."\0".'affectations' => [parent::class, 'affectations', null],
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        'actif' => [parent::class, 'actif', null],
        'affectations' => [parent::class, 'affectations', null],
        'dateNaissance' => [parent::class, 'dateNaissance', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'poste' => [parent::class, 'poste', null],
        'prenom' => [parent::class, 'prenom', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
