<?php

namespace ContainerSZeO6FE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JO4GrNHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JO4GrNH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JO4GrNH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aff' => ['privates', '.errored..service_locator.JO4GrNH.App\\Entity\\Affectation', NULL, 'Cannot autowire service ".service_locator.JO4GrNH": it needs an instance of "App\\Entity\\Affectation" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'aff' => 'App\\Entity\\Affectation',
            'em' => '?',
        ]);
    }
}
