<?php

namespace ContainerY2AnnPK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QIWwJJiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qIWwJJi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qIWwJJi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AffectationController::delete' => ['privates', '.service_locator.dOY9ozk', 'get_ServiceLocator_DOY9ozkService', true],
            'App\\Controller\\AffectationController::edit' => ['privates', '.service_locator.dOY9ozk', 'get_ServiceLocator_DOY9ozkService', true],
            'App\\Controller\\AffectationController::index' => ['privates', '.service_locator.7XSAMv0', 'get_ServiceLocator_7XSAMv0Service', true],
            'App\\Controller\\AffectationController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AffectationController::show' => ['privates', '.service_locator.w7RyIPL', 'get_ServiceLocator_W7RyIPLService', true],
            'App\\Controller\\CollaborateurController::delete' => ['privates', '.service_locator.gv8l6lm', 'get_ServiceLocator_Gv8l6lmService', true],
            'App\\Controller\\CollaborateurController::edit' => ['privates', '.service_locator.gv8l6lm', 'get_ServiceLocator_Gv8l6lmService', true],
            'App\\Controller\\CollaborateurController::index' => ['privates', '.service_locator.YiuYd7T', 'get_ServiceLocator_YiuYd7TService', true],
            'App\\Controller\\CollaborateurController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CollaborateurController::show' => ['privates', '.service_locator.Yb3Rv_S', 'get_ServiceLocator_Yb3RvSService', true],
            'App\\Controller\\MissionController::delete' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController::edit' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController::index' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MissionController::show' => ['privates', '.service_locator.DzSeb2e', 'get_ServiceLocator_DzSeb2eService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AffectationController:delete' => ['privates', '.service_locator.dOY9ozk', 'get_ServiceLocator_DOY9ozkService', true],
            'App\\Controller\\AffectationController:edit' => ['privates', '.service_locator.dOY9ozk', 'get_ServiceLocator_DOY9ozkService', true],
            'App\\Controller\\AffectationController:index' => ['privates', '.service_locator.7XSAMv0', 'get_ServiceLocator_7XSAMv0Service', true],
            'App\\Controller\\AffectationController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AffectationController:show' => ['privates', '.service_locator.w7RyIPL', 'get_ServiceLocator_W7RyIPLService', true],
            'App\\Controller\\CollaborateurController:delete' => ['privates', '.service_locator.gv8l6lm', 'get_ServiceLocator_Gv8l6lmService', true],
            'App\\Controller\\CollaborateurController:edit' => ['privates', '.service_locator.gv8l6lm', 'get_ServiceLocator_Gv8l6lmService', true],
            'App\\Controller\\CollaborateurController:index' => ['privates', '.service_locator.YiuYd7T', 'get_ServiceLocator_YiuYd7TService', true],
            'App\\Controller\\CollaborateurController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CollaborateurController:show' => ['privates', '.service_locator.Yb3Rv_S', 'get_ServiceLocator_Yb3RvSService', true],
            'App\\Controller\\MissionController:delete' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController:edit' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController:index' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MissionController:show' => ['privates', '.service_locator.DzSeb2e', 'get_ServiceLocator_DzSeb2eService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AffectationController::delete' => '?',
            'App\\Controller\\AffectationController::edit' => '?',
            'App\\Controller\\AffectationController::index' => '?',
            'App\\Controller\\AffectationController::new' => '?',
            'App\\Controller\\AffectationController::show' => '?',
            'App\\Controller\\CollaborateurController::delete' => '?',
            'App\\Controller\\CollaborateurController::edit' => '?',
            'App\\Controller\\CollaborateurController::index' => '?',
            'App\\Controller\\CollaborateurController::new' => '?',
            'App\\Controller\\CollaborateurController::show' => '?',
            'App\\Controller\\MissionController::delete' => '?',
            'App\\Controller\\MissionController::edit' => '?',
            'App\\Controller\\MissionController::index' => '?',
            'App\\Controller\\MissionController::new' => '?',
            'App\\Controller\\MissionController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AffectationController:delete' => '?',
            'App\\Controller\\AffectationController:edit' => '?',
            'App\\Controller\\AffectationController:index' => '?',
            'App\\Controller\\AffectationController:new' => '?',
            'App\\Controller\\AffectationController:show' => '?',
            'App\\Controller\\CollaborateurController:delete' => '?',
            'App\\Controller\\CollaborateurController:edit' => '?',
            'App\\Controller\\CollaborateurController:index' => '?',
            'App\\Controller\\CollaborateurController:new' => '?',
            'App\\Controller\\CollaborateurController:show' => '?',
            'App\\Controller\\MissionController:delete' => '?',
            'App\\Controller\\MissionController:edit' => '?',
            'App\\Controller\\MissionController:index' => '?',
            'App\\Controller\\MissionController:new' => '?',
            'App\\Controller\\MissionController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
