<?php

namespace ContainerWgvaSDl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAffectation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.w7RyIPL.App\Entity\Affectation' shared service.
     *
     * @return \App\Entity\Affectation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.w7RyIPL": it needs an instance of "App\\Entity\\Affectation" but this type has been excluded in "config/services.yaml".');
    }
}
