<?php

namespace ContainerV1sZoid;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4AI9MLrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4AI9MLr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4AI9MLr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aff' => ['privates', '.errored..service_locator.4AI9MLr.App\\Entity\\Affectation', NULL, 'Cannot autowire service ".service_locator.4AI9MLr": it needs an instance of "App\\Entity\\Affectation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'aff' => 'App\\Entity\\Affectation',
        ]);
    }
}
