<?php

namespace ContainerV1sZoid;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollaborateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gv8l6lm.App\Entity\Collaborateur' shared service.
     *
     * @return \App\Entity\Collaborateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gv8l6lm": it needs an instance of "App\\Entity\\Collaborateur" but this type has been excluded in "config/services.yaml".');
    }
}
