<?php

namespace ContainerVyBxWWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W7RyIPLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w7RyIPL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w7RyIPL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'affectation' => ['privates', '.errored..service_locator.w7RyIPL.App\\Entity\\Affectation', NULL, 'Cannot autowire service ".service_locator.w7RyIPL": it needs an instance of "App\\Entity\\Affectation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'affectation' => 'App\\Entity\\Affectation',
        ]);
    }
}
