<?php

namespace ContainerJzgv0gy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gv8l6lmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gv8l6lm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gv8l6lm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collaborateur' => ['privates', '.errored..service_locator.gv8l6lm.App\\Entity\\Collaborateur', NULL, 'Cannot autowire service ".service_locator.gv8l6lm": it needs an instance of "App\\Entity\\Collaborateur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'collaborateur' => 'App\\Entity\\Collaborateur',
            'entityManager' => '?',
        ]);
    }
}
